/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawyersIndexRouteImport } from './routes/lawyers.index'
import { Route as LawyersLawyerIdRouteImport } from './routes/lawyers.$lawyerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersIndexRoute = LawyersIndexRouteImport.update({
  id: '/lawyers/',
  path: '/lawyers/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersLawyerIdRoute = LawyersLawyerIdRouteImport.update({
  id: '/lawyers/$lawyerId',
  path: '/lawyers/$lawyerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/lawyers/': typeof LawyersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/lawyers': typeof LawyersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lawyers/$lawyerId': typeof LawyersLawyerIdRoute
  '/lawyers/': typeof LawyersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lawyers/$lawyerId' | '/lawyers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lawyers/$lawyerId' | '/lawyers'
  id: '__root__' | '/' | '/lawyers/$lawyerId' | '/lawyers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LawyersLawyerIdRoute: typeof LawyersLawyerIdRoute
  LawyersIndexRoute: typeof LawyersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers/': {
      id: '/lawyers/'
      path: '/lawyers'
      fullPath: '/lawyers/'
      preLoaderRoute: typeof LawyersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers/$lawyerId': {
      id: '/lawyers/$lawyerId'
      path: '/lawyers/$lawyerId'
      fullPath: '/lawyers/$lawyerId'
      preLoaderRoute: typeof LawyersLawyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LawyersLawyerIdRoute: LawyersLawyerIdRoute,
  LawyersIndexRoute: LawyersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
